apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: my-backend-app
  description: |
    my-backend-app.
  links:
    - url: https://www.notion.so/roadie/Sample-Service-e067465e56a14ae9b0507f8559f6aa26
      title: What is the Passenger Backend?
      icon: help
    - url: https://www.notion.so/roadie/Sample-Service-e067465e56a14ae9b0507f8559f6aa26
      title: Grafana
    - url: https://www.notion.so/roadie/Sample-Service-e067465e56a14ae9b0507f8559f6aa26
      title: Datadog
      icon: dashboard
  annotations:
    github.com/project-slug: RoadieHQ/sample-service
    sentry.io/project-slug: sample-service
    cloud.google.com/function-ids: projects/roadie-dev-283705/locations/europe-west1/functions/test-fn-1
    backstage.io/techdocs-ref: url:https://github.com/RoadieHQ/sample-service/tree/main
    pagerduty.com/integration-key: 1cf15c07f6f440e0a8d65b7ce80be834
    snyk.io/org-name: roadie
    snyk.io/project-ids: 63ac09c4-fd65-4f53-b9b2-c31d2dee3291
    backstage.io/kubernetes-id: sample-service
spec:
  type: service
  owner: vaibhav
  lifecycle: production
  system: passengers
  providesApis:
    - my-api
  dependsOn:
    - Component:my-app-module
